# /config.py

# --- Parámetros Generales ---
REFRESH_SECONDS = 300
MIN_24H_VOLUME_USD = 5_000_000 # <-- Esta es la variable del error
TIMEFRAME_ANALYSIS = '5m'
WATCHLIST_SIZE = 10 # <-- El Top 10 de sospechosos

# --- Parámetros de Análisis Profundo (FASE 2) ---
REVERSAL_TIMEFRAME = '15m'
OHLCV_LIMIT = 100
ACCEL_LOOKBACK_CANDLES = 3
ACCEL_VOLUME_MULT = 2.0
ACCEL_CHANGE_PCT = 1.5
REVERSAL_LOOKBACK_MINS = 30
REVERSAL_VOLUME_MULT = 2.5
REVERSAL_WICK_MULT = 1.5